version: '3'
services:
  laravel-nginx:
    container_name: "laravel-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  laravel-app:
    container_name: "laravel-app"
    build:
      context: ./docker/php
    depends_on:
      - laravel-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  laravel-mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "laravel-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    ports:
      - 3306:3306

  laravel-redis:
    image: redis:alpine
    container_name: "laravel-redis"
    ports:
      - 16379:6379
